# -*- coding: utf-8 -*-
{
    'name': "Employee Base",
    'description': "Employee Base",
    'author': "Stefanini Sysman SAS",
    'website': "https://sysman.com.co",

    'category': 'Human Resources',
    'version': '15.0.1.0.0',

    # any module necessary for this one to work correctly
    'depends': [
        'contacts',
        'l10n_co_extended',
        'hr_contract',
        'hr_payroll',
        'hr_skills',
        'hr_recruitment_survey',
        'hr_recruitment_reason',
        'base_address_city',
        'web',
               
    ],

    # always loaded
    'data': [
        'security/ir.model.access.csv',
        'views/hr_applicant_views.xml',
        'views/hr_requisition_views.xml',
        'views/hr_employee_unit_views.xml',
        'views/hr_employee_address_views.xml',
        'views/hr_employee_phobia_views.xml',
        'views/hr_employee_son_views.xml',
        'views/hr_job_views.xml',
        'views/hr_employee_education_views.xml',
        'views/hr_job_asset_views.xml',
        'views/hr_employee_pet_views.xml',
        'views/hr_employee_allergy_views.xml',
        'views/hr_employee_lang_views.xml',
        'views/hr_employee_hobby_views.xml',
        'views/hr_employee_views.xml',
        'views/hr_employee_cost_center_views.xml',
        'views/hr_contract_views.xml',
        'views/hr_resume_line_views.xml',
        'views/hr_employee_payrollcc_views.xml',
        'views/hr_employee_contributor_type_views.xml',
        'views/hr_employee_salary_type_views.xml',
        'views/hr_employee_division_views.xml',
        'views/hr_employee_area_views.xml',
        'views/hr_employee_time_eval_views.xml',
        'views/res_partner_views.xml',
        'views/survey_survey_views.xml',
        'views/ir_actions_report_views.xml',
        'views/hr_partner_bank_views.xml',
        'views/hr_job_training_views.xml',
        'views/hr_risk_type_view.xml',
        'views/hr_contract_type_views.xml',
        'views/hr_recruitment_reason_views.xml',
        'views/hr_disability_handling_views.xml',
        'views/hr_employee_shift_type_views.xml',
        'views/hr_job_type_views.xml',
        'views/hr_job_role_views.xml',
        'views/hr_recruitment_stage_views.xml',
        'views/res_relationship_views.xml',
        'views/res_users_views.xml',
        'data/requisition_stage_data.xml',
        'data/hr_recruitment_reason_data.xml',
        'data/recruitment_stage_data.xml',
        'data/departure_reason_data.xml',
        'data/hr_contract_type_data.xml',
        'data/hr_disability_handling_data.xml',
        'data/hr_employee_shift_type_data.xml',
        'data/hr_job_type_data.xml',
        'data/hr_risk_type_data.xml',
        'data/mail_template_data.xml',
        'wizard/survey_wizard.xml',
        'wizard/survey_print_wizard.xml',
    ],
}