from . import hr_applicant
from . import hr_requisition
from . import hr_employee_son
from . import hr_job
from . import hr_employee_education
from . import hr_job_asset
from . import hr_employee
from . import hr_employee_misc
from . import hr_contract
from . import hr_resume_line
from . import res_partner
from . import hr_recruitment_stage
from . import survey
from . import ir_actions_report
from . import res_partner_bank
from . import hr_job_training
from . import hr_recruitment_reason
from . import res_users